{
  "openapi": "3.0.1",
  "components": {
    "schemas": {
      "FlowBaseInfo": {
        "type": "object",
        "properties": {
          "fdr": {
            "type": "string"
          },
          "created": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          }
        }
      },
      "FlowContentResponse": {
        "type": "object",
        "properties": {
          "dateFrom": {
            "$ref": "#/components/schemas/LocalDate"
          },
          "dateTo": {
            "$ref": "#/components/schemas/LocalDate"
          },
          "data": {
            "type": "string"
          }
        }
      },
      "InfoResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The identificative name of the deployed application"
          },
          "version": {
            "type": "string",
            "description": "The current version of the deployed application"
          },
          "environment": {
            "type": "string",
            "description": "The current environment where the application is deployed"
          },
          "description": {
            "type": "string",
            "description": "The descriptive information related to the info response"
          }
        }
      },
      "LocalDate": {
        "type": "string",
        "format": "date"
      },
      "MultipleFlowsOnSingleDateResponse": {
        "type": "object",
        "properties": {
          "date": {
            "$ref": "#/components/schemas/LocalDate"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowBaseInfo"
            }
          }
        }
      },
      "MultipleFlowsResponse": {
        "type": "object",
        "properties": {
          "dateFrom": {
            "$ref": "#/components/schemas/LocalDate"
          },
          "dateTo": {
            "$ref": "#/components/schemas/LocalDate"
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FlowBaseInfo"
            }
          }
        }
      },
      "ProblemJson": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable"
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "description": "The HTTP status code generated by the origin server for this occurrence of the problem.",
            "maximum": 600,
            "minimum": 100
          },
          "details": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the problem."
          }
        }
      }
    },
    "responses": {
      "ErrorResponse400": {
        "description": "Default app exception for status 400",
        "content": {
          "application/json": {
            "example": {
              "httpStatusCode": 400,
              "httpStatusDescription": "Bad Request",
              "appErrorCode": "FDR-XXXX",
              "errors": [
                {
                  "path": "<detail.path.if-exist>",
                  "message": "<detail.message>"
                }
              ]
            },
            "schema": {
              "$ref": "#/components/schemas/ProblemJson"
            }
          }
        }
      },
      "ErrorResponse404": {
        "description": "Default app exception for status 404",
        "content": {
          "application/json": {
            "example": {
              "httpStatusCode": 404,
              "httpStatusDescription": "Not Found",
              "appErrorCode": "FDR-XXXX",
              "errors": [
                {
                  "message": "<detail.message>"
                }
              ]
            },
            "schema": {
              "$ref": "#/components/schemas/ProblemJson"
            }
          }
        }
      },
      "ErrorResponse500": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "example": {
              "errorId": "50905466-1881-457b-b42f-fb7b2bfb1610",
              "httpStatusCode": 500,
              "httpStatusDescription": "Internal Server Error",
              "appErrorCode": "FDR-0500",
              "errors": [
                {
                  "message": "An unexpected error has occurred. Please contact support."
                }
              ]
            },
            "schema": {
              "$ref": "#/components/schemas/ProblemJson"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "name": "Ocp-Apim-Subscription-Key",
        "in": "header"
      }
    }
  },
  "info": {
    "termsOfService": "https://www.pagopa.gov.it/",
    "title": "Fdr technical support - Api (TEST)",
    "version": "1.1.3"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Localhost base URL"
    },
    {
      "url": "https://{host}/technical-support/fdr/api/v1",
      "description": "Base URL",
      "variables": {
        "host": {
          "description": "Environment host",
          "enum": [
            "api.dev.platform.pagopa.it",
            "api.uat.platform.pagopa.it",
            "api.platform.pagopa.it"
          ],
          "default": "api.dev.platform.pagopa.it"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Info",
      "description": "Info operations"
    },
    {
      "name": "Organization",
      "description": "APIs for inspecting creditor institution usage of flows"
    },
    {
      "name": "PSP",
      "description": "APIs for inspecting PSP usage of flows"
    }
  ],
  "paths": {
    "/info": {
      "get": {
        "summary": "Health-check",
        "operationId": "IInfoController_healthCheck",
        "tags": [
          "Info"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InfoResponse"
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/organizations/{organizationId}/flows/{flowId}": {
      "get": {
        "summary": "This API allow to retrieve all revision of a FdR for a specific CI",
        "operationId": "IOrganizationController_getRevisions",
        "tags": [
          "Organization"
        ],
        "parameters": [
          {
            "description": "The flow name, used as a search filter",
            "example": "2025-01-0188888888888-0001",
            "required": true,
            "name": "flowId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The organization fiscal code, used as a search filter",
            "example": "99999999999",
            "required": true,
            "name": "organizationId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The starting date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ending date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "404": {
            "$ref": "#/components/responses/ErrorResponse404"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/organizations/{organizationId}/psps/{pspId}/download": {
      "get": {
        "summary": "This API allow to retrieve a list of download tentative of FdR for a specific date",
        "operationId": "IOrganizationController_getDownloads",
        "tags": [
          "Organization"
        ],
        "parameters": [
          {
            "description": "The organization fiscal code, used as a search filter",
            "example": "99999999999",
            "required": true,
            "name": "organizationId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The date for retrieving FdR download tentative",
            "example": "2025-03-10",
            "name": "date",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The flow name, used as a search filter",
            "example": "2025-01-0188888888888-0001",
            "name": "flowName",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsOnSingleDateResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "404": {
            "$ref": "#/components/responses/ErrorResponse404"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/organizations/{organizationId}/psps/{pspId}/flows/{flowId}/revisions/{revision}": {
      "get": {
        "summary": "This API allow to retrieve a revision of a FdR for a specific CI and PSP",
        "operationId": "IOrganizationController_getFlow",
        "tags": [
          "Organization"
        ],
        "parameters": [
          {
            "description": "The flow name, used as a search filter",
            "example": "2025-01-0188888888888-0001",
            "required": true,
            "name": "flowId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The organization fiscal code, used as a search filter",
            "example": "99999999999",
            "required": true,
            "name": "organizationId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The FdR revision, used as a search filter",
            "example": "1",
            "required": true,
            "name": "revision",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The starting date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ending date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The expected FdR format, based of this parameter the flow is retrieved from FdR-1 (xml) or FdR-3 (json)",
            "example": "xml",
            "name": "fileType",
            "in": "query",
            "schema": {
              "type": "string",
              "default": "json"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FlowContentResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "404": {
            "$ref": "#/components/responses/ErrorResponse404"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/organizations/{organizationId}/psps/{pspId}/upload": {
      "get": {
        "summary": "This API allow to retrieve a list of upload tentative of FdR for a specific date",
        "operationId": "IOrganizationController_getUploads",
        "tags": [
          "Organization"
        ],
        "parameters": [
          {
            "description": "The organization fiscal code, used as a search filter",
            "example": "99999999999",
            "required": true,
            "name": "organizationId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The date for retrieving FdR upload tentative",
            "example": "2025-03-10",
            "name": "date",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The flow name, used as a search filter",
            "example": "2025-01-0188888888888-0001",
            "name": "flowName",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsOnSingleDateResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "404": {
            "$ref": "#/components/responses/ErrorResponse404"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/psps/{pspId}": {
      "get": {
        "summary": "This API allow to retrieve a list of FdR for a specific PSP",
        "operationId": "IPSPController_searchFlowByPsp",
        "tags": [
          "PSP"
        ],
        "parameters": [
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The starting date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ending date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The flow name, used as a search filter",
            "example": "2025-01-0188888888888-0001",
            "name": "flowId",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The organization fiscal code, used as a search filter",
            "example": "99999999999",
            "name": "organizationId",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/psps/{pspId}/iur/{iur}": {
      "get": {
        "summary": "This API allow to retrieve a list of FdR for a specific PSP and IUV",
        "operationId": "IPSPController_searchFlowByPspAndIur",
        "tags": [
          "PSP"
        ],
        "parameters": [
          {
            "description": "The payment's IUR code, used as a search filter",
            "example": "17854456582215",
            "name": "iur",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The starting date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ending date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    },
    "/psps/{pspId}/iuv/{iuv}": {
      "get": {
        "summary": "This API allow to retrieve a list of FdR for a specific PSP and IUV",
        "operationId": "IPSPController_searchFlowByPspAndIuv",
        "tags": [
          "PSP"
        ],
        "parameters": [
          {
            "description": "The payment's IUV code, used as a search filter",
            "example": "17854456582215",
            "name": "iuv",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^(.{1,35})$"
            }
          },
          {
            "description": "The PSP identifier, used as a search filter",
            "example": "88888888888",
            "required": true,
            "name": "pspId",
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The starting date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateFrom",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ending date for retrieving flows",
            "example": "2025-03-10",
            "name": "dateTo",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/LocalDate"
            }
          },
          {
            "description": "The ID of an EC",
            "name": "organizationId",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MultipleFlowsResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorResponse400"
          },
          "500": {
            "$ref": "#/components/responses/ErrorResponse500"
          }
        }
      }
    }
  }
}
